# Generated by Django 5.2.10 on 2026-02-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
