# Generated by Django 5.2.10 on 2026-02-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_userprofile_address_remove_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
    ]
