# chocho# Generated by Django 5.2.10 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="delivery_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
